
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 522823 bytes/channel
 *	Total Size: 1 * 522823 + 4 (header) = 522867 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mohammed/Desktop/gameMusic.wav
 *	Time-stamp: Tue Apr 10 18:31:01 2018
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 522823

extern const unsigned char gameMusic[522823];

#endif /* __GAMEMUSICH__ */
