
/**************************************************************
 *	
 *	kaching, 8 bit, 11025Hz,
 *	1 channel, 8609 bytes/channel
 *	Total Size: 1 * 8609 + 4 (header) = 8653 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mohammed/Desktop/kaching.wav
 *	Time-stamp: Sun Apr 15 19:10:54 2018
 *	
 **************************************************************/

#ifndef __KACHINGH__
#define __KACHINGH__

#define KACHINGFREQ 11025
#define KACHINGLEN 8609

extern const unsigned char kaching[8609];

#endif /* __KACHINGH__ */
