
/**************************************************************
 *	
 *	menuSFX, 8 bit, 11025Hz,
 *	1 channel, 1701 bytes/channel
 *	Total Size: 1 * 1701 + 4 (header) = 1745 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mohammed/Desktop/menuSFX.wav
 *	Time-stamp: Tue Apr 10 18:57:08 2018
 *	
 **************************************************************/

#ifndef __MENUSFXH__
#define __MENUSFXH__

#define MENUSFXFREQ 11025
#define MENUSFXLEN 1701

extern const unsigned char menuSFX[1701];

#endif /* __MENUSFXH__ */
