
/**************************************************************
 *	
 *	priceSFX, 8 bit, 11025Hz,
 *	1 channel, 1648 bytes/channel
 *	Total Size: 1 * 1648 + 4 (header) = 1692 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mohammed/Desktop/priceSFX.wav
 *	Time-stamp: Tue Apr 10 19:12:45 2018
 *	
 **************************************************************/

#ifndef __PRICESFXH__
#define __PRICESFXH__

#define PRICESFXFREQ 11025
#define PRICESFXLEN 1648

extern const unsigned char priceSFX[1648];

#endif /* __PRICESFXH__ */
